CREATE TABLE INVESTMENT  
( 	
	"ID" NUMBER(10) NOT NULL ,  
	"NAME" VARCHAR2(200 BYTE) NOT NULL,  
	"LEGAL_CLOSE_DATE" DATE,
	"TAX_ID" VARCHAR2(200 BYTE),
	"COMMITMENT_AMOUNT" NUMBER, 
	"RELATIONSHIP_CLIENT" VARCHAR2(200 BYTE),
	"PORTFOLIO_TYPE" VARCHAR2(200 BYTE),
	"SYNDICATOR" VARCHAR2(200 BYTE), 	 	
	CONSTRAINT "INVESTMENT_PK" PRIMARY KEY  ("ID")  
); 


CREATE TABLE INVESTOR  
( 	
	"ID" NUMBER(10) NOT NULL ,  
	"NAME" VARCHAR2(200 BYTE) NOT NULL,  
	"OWNERSHIP" VARCHAR2(200 BYTE),
	"BLA_ONE" VARCHAR2(200 BYTE),
	"INVESTMENT_ID" NUMBER, 	
	CONSTRAINT "INVESTOR_PK" PRIMARY KEY  ("ID")  
);  


//Run one by one
CREATE SEQUENCE INVESTMENT_SEQUANCE;

CREATE OR REPLACE TRIGGER INVESTMENT_ON_INSERT
  BEFORE INSERT ON INVESTMENT
  FOR EACH ROW
BEGIN
  SELECT INVESTMENT_SEQUANCE.nextval
  INTO :new.id
  FROM dual;
END;


CREATE SEQUENCE INVESTOR_SEQUANCE;

CREATE OR REPLACE TRIGGER INVESTOR_ON_INSERT
  BEFORE INSERT ON INVESTOR
  FOR EACH ROW
BEGIN
  SELECT INVESTOR_SEQUANCE.nextval
  INTO :new.id
  FROM dual;
END;



